### ISSUE TITLE
fix: [Ver.0.51] レイヤーを追加した後にそのレイヤーを選択するとエラーが発生する

### ISSUE THREAD

**Issue by gckohaku** [gckohaku/WebClock#93]
## 現象
レイヤー追加後に、その追加したレイヤーを選択すると、エラーが出て動かなくなる
追加したレイヤー以外を選択してもエラーが出ない
複数追加した場合は、追加したレイヤーのどれかを選択するとエラーが出る

## 情報
`calcBorderArea.ts` に定義した関数内でエラーが出ている
既にあったレイヤーの場合、引数 `params` の型が `DotsOnCircleParameters` を継承したクラスになっているが、追加したレイヤーの場合は `Proxy(Object)` になっている

## エラーメッセージ
```
Uncaught (in promise) TypeError: params.getParameterValue is not a function
    at Object.AnalogRoundedAlignedHandArea [as 丸針 (Bタイプ)] (http://localhost:5173/WebClock/src/common/scripts/input_data_contents/calcBorderArea.ts?t=1716362331149:51:33)
    at Proxy.<anonymous> (ClockDisplay.vue:41:98)
    at ClockDisplay.vue:107:58
    at renderList (chunk-AZ23VQUG.js?v=05251d6b:4357:16)
    at Proxy._sfc_render (ClockDisplay.vue:1:1)
    at renderComponentRoot (chunk-AZ23VQUG.js?v=05251d6b:2350:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-AZ23VQUG.js?v=05251d6b:7549:26)
    at ReactiveEffect.run (chunk-AZ23VQUG.js?v=05251d6b:434:19)
    at instance.update (chunk-AZ23VQUG.js?v=05251d6b:7602:17)
    at callWithErrorHandling (chunk-AZ23VQUG.js?v=05251d6b:1659:33)
```

**Comment by gckohaku** [comment]
エラーの原因が分かった
https://github.com/gckohaku/WebClock/blob/e1a62fca893030c0969af7a1102c13a2160e1dd9/src/components/ParameterSettingSidebar.vue#L50
これの `Object.assign` が原因だった
そもそもなんでこういう実装にしていたんだっけ．．．

**Comment by gckohaku** [comment]
てなわけで `Object.assign` を使わずにそのまま push したら直った。
